/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillItem {
  'priceAtSale' : bigint,
  'variantId' : bigint,
  'quantity' : bigint,
}
export type BillStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'finalized' : null };
export interface BillToken {
  'id' : bigint,
  'status' : BillStatus,
  'businessId' : bigint,
  'createdAt' : bigint,
  'finalizedAt' : [] | [bigint],
  'totalAmount' : bigint,
  'items' : Array<BillItem>,
  'salesmanId' : bigint,
}
export interface Business {
  'id' : bigint,
  'trialEndDate' : bigint,
  'owner' : Principal,
  'name' : string,
  'businessType' : BusinessType,
  'subscriptionStatus' : SubscriptionStatus,
  'trialStartDate' : bigint,
}
export type BusinessType = { 'clothing' : null } |
  { 'groceries' : null } |
  { 'general' : null } |
  { 'electronics' : null };
export type ExternalBlob = Uint8Array;
export type InviteStatus = { 'revoked' : null } |
  { 'pending' : null } |
  { 'accepted' : null };
export interface Product {
  'id' : bigint,
  'sku' : string,
  'imageUrls' : Array<ExternalBlob>,
  'businessId' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
}
export type ProductState = { 'sold' : null } |
  { 'locked' : null } |
  { 'available' : null };
export interface ProductVariant {
  'id' : bigint,
  'variantName' : string,
  'productId' : bigint,
  'stockCount' : bigint,
  'state' : ProductState,
  'lockedBy' : [] | [bigint],
}
export type Role = { 'salesman' : null } |
  { 'owner' : null };
export interface SalesmanActivityLog {
  'action' : string,
  'businessId' : bigint,
  'metadata' : string,
  'logId' : bigint,
  'timestamp' : bigint,
  'salesmanId' : bigint,
}
export interface SalesmanInvite {
  'id' : bigint,
  'status' : InviteStatus,
  'contactInfo' : string,
  'businessId' : bigint,
  'invitedAt' : bigint,
}
export type SubscriptionStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'expired' : null } |
  { 'grace' : null };
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'businessId' : bigint,
  'userId' : bigint,
  'name' : string,
  'role' : Role,
  'isActive' : boolean,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [bigint, string, string, string, string, Array<ExternalBlob>, boolean],
    bigint
  >,
  'addProductVariant' : ActorMethod<
    [bigint, string, bigint, ProductState],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBill' : ActorMethod<[bigint], undefined>,
  'createBillToken' : ActorMethod<[bigint, Array<BillItem>, bigint], bigint>,
  'deactivateSalesman' : ActorMethod<[bigint], undefined>,
  'editProduct' : ActorMethod<
    [bigint, string, string, string, string, Array<ExternalBlob>, boolean],
    undefined
  >,
  'editProductVariant' : ActorMethod<[bigint, string, bigint], undefined>,
  'finalizeBill' : ActorMethod<[bigint], undefined>,
  'getActivityLogs' : ActorMethod<[bigint], Array<SalesmanActivityLog>>,
  'getAllBills' : ActorMethod<[], Array<BillToken>>,
  'getAllBusinesses' : ActorMethod<[], Array<Business>>,
  'getAllProductVariants' : ActorMethod<[], Array<ProductVariant>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBillsForBusiness' : ActorMethod<[bigint], Array<BillToken>>,
  'getBusiness' : ActorMethod<[bigint], Business>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvitesForBusiness' : ActorMethod<[bigint], Array<SalesmanInvite>>,
  'getPendingBills' : ActorMethod<[bigint], Array<BillToken>>,
  'getProductsForBusiness' : ActorMethod<[bigint], Array<Product>>,
  'getSalesmanActivityLogs' : ActorMethod<[bigint], Array<SalesmanActivityLog>>,
  'getTimeDiff' : ActorMethod<[Time, Time], bigint>,
  'getTotalBillsCount' : ActorMethod<[bigint], bigint>,
  'getTotalSales' : ActorMethod<[bigint], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVariantsForProduct' : ActorMethod<[bigint], Array<ProductVariant>>,
  'inviteSalesman' : ActorMethod<[bigint, string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lockVariant' : ActorMethod<[bigint], undefined>,
  'lookupInvite' : ActorMethod<[string], [] | [SalesmanInvite]>,
  'registerBusiness' : ActorMethod<
    [string, BusinessType, SubscriptionStatus, bigint, bigint],
    bigint
  >,
  'releaseVariantLock' : ActorMethod<[bigint], undefined>,
  'revokeInvite' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [
      {
        'businessId' : bigint,
        'name' : string,
        'role' : Role,
        'isActive' : boolean,
        'email' : string,
        'phone' : string,
      },
    ],
    undefined
  >,
  'updateSubscription' : ActorMethod<[bigint, SubscriptionStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];