/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductState = IDL.Variant({
  'sold' : IDL.Null,
  'locked' : IDL.Null,
  'available' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BillItem = IDL.Record({
  'priceAtSale' : IDL.Nat,
  'variantId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const SalesmanActivityLog = IDL.Record({
  'action' : IDL.Text,
  'businessId' : IDL.Nat,
  'metadata' : IDL.Text,
  'logId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'salesmanId' : IDL.Nat,
});
export const BillStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'finalized' : IDL.Null,
});
export const BillToken = IDL.Record({
  'id' : IDL.Nat,
  'status' : BillStatus,
  'businessId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'finalizedAt' : IDL.Opt(IDL.Int),
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(BillItem),
  'salesmanId' : IDL.Nat,
});
export const BusinessType = IDL.Variant({
  'clothing' : IDL.Null,
  'groceries' : IDL.Null,
  'general' : IDL.Null,
  'electronics' : IDL.Null,
});
export const SubscriptionStatus = IDL.Variant({
  'trial' : IDL.Null,
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'grace' : IDL.Null,
});
export const Business = IDL.Record({
  'id' : IDL.Nat,
  'trialEndDate' : IDL.Int,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'businessType' : BusinessType,
  'subscriptionStatus' : SubscriptionStatus,
  'trialStartDate' : IDL.Int,
});
export const ProductVariant = IDL.Record({
  'id' : IDL.Nat,
  'variantName' : IDL.Text,
  'productId' : IDL.Nat,
  'stockCount' : IDL.Nat,
  'state' : ProductState,
  'lockedBy' : IDL.Opt(IDL.Nat),
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'imageUrls' : IDL.Vec(ExternalBlob),
  'businessId' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
});
export const Role = IDL.Variant({ 'salesman' : IDL.Null, 'owner' : IDL.Null });
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'businessId' : IDL.Nat,
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : Role,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const InviteStatus = IDL.Variant({
  'revoked' : IDL.Null,
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
});
export const SalesmanInvite = IDL.Record({
  'id' : IDL.Nat,
  'status' : InviteStatus,
  'contactInfo' : IDL.Text,
  'businessId' : IDL.Nat,
  'invitedAt' : IDL.Int,
});
export const Time = IDL.Int;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(ExternalBlob),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'addProductVariant' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, ProductState],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBill' : IDL.Func([IDL.Nat], [], []),
  'createBillToken' : IDL.Func(
      [IDL.Nat, IDL.Vec(BillItem), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deactivateSalesman' : IDL.Func([IDL.Nat], [], []),
  'editProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(ExternalBlob),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'editProductVariant' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'finalizeBill' : IDL.Func([IDL.Nat], [], []),
  'getActivityLogs' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SalesmanActivityLog)],
      ['query'],
    ),
  'getAllBills' : IDL.Func([], [IDL.Vec(BillToken)], ['query']),
  'getAllBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
  'getAllProductVariants' : IDL.Func([], [IDL.Vec(ProductVariant)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBillsForBusiness' : IDL.Func([IDL.Nat], [IDL.Vec(BillToken)], ['query']),
  'getBusiness' : IDL.Func([IDL.Nat], [Business], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvitesForBusiness' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SalesmanInvite)],
      ['query'],
    ),
  'getPendingBills' : IDL.Func([IDL.Nat], [IDL.Vec(BillToken)], ['query']),
  'getProductsForBusiness' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getSalesmanActivityLogs' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SalesmanActivityLog)],
      ['query'],
    ),
  'getTimeDiff' : IDL.Func([Time, Time], [IDL.Int], ['query']),
  'getTotalBillsCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getTotalSales' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVariantsForProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductVariant)],
      ['query'],
    ),
  'inviteSalesman' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lockVariant' : IDL.Func([IDL.Nat], [], []),
  'lookupInvite' : IDL.Func([IDL.Text], [IDL.Opt(SalesmanInvite)], ['query']),
  'registerBusiness' : IDL.Func(
      [IDL.Text, BusinessType, SubscriptionStatus, IDL.Int, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'releaseVariantLock' : IDL.Func([IDL.Nat], [], []),
  'revokeInvite' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Role, IDL.Bool],
      [],
      [],
    ),
  'updateSubscription' : IDL.Func([IDL.Nat, SubscriptionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductState = IDL.Variant({
    'sold' : IDL.Null,
    'locked' : IDL.Null,
    'available' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BillItem = IDL.Record({
    'priceAtSale' : IDL.Nat,
    'variantId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const SalesmanActivityLog = IDL.Record({
    'action' : IDL.Text,
    'businessId' : IDL.Nat,
    'metadata' : IDL.Text,
    'logId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'salesmanId' : IDL.Nat,
  });
  const BillStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'finalized' : IDL.Null,
  });
  const BillToken = IDL.Record({
    'id' : IDL.Nat,
    'status' : BillStatus,
    'businessId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'finalizedAt' : IDL.Opt(IDL.Int),
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(BillItem),
    'salesmanId' : IDL.Nat,
  });
  const BusinessType = IDL.Variant({
    'clothing' : IDL.Null,
    'groceries' : IDL.Null,
    'general' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const SubscriptionStatus = IDL.Variant({
    'trial' : IDL.Null,
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'grace' : IDL.Null,
  });
  const Business = IDL.Record({
    'id' : IDL.Nat,
    'trialEndDate' : IDL.Int,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'businessType' : BusinessType,
    'subscriptionStatus' : SubscriptionStatus,
    'trialStartDate' : IDL.Int,
  });
  const ProductVariant = IDL.Record({
    'id' : IDL.Nat,
    'variantName' : IDL.Text,
    'productId' : IDL.Nat,
    'stockCount' : IDL.Nat,
    'state' : ProductState,
    'lockedBy' : IDL.Opt(IDL.Nat),
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'imageUrls' : IDL.Vec(ExternalBlob),
    'businessId' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  const Role = IDL.Variant({ 'salesman' : IDL.Null, 'owner' : IDL.Null });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'businessId' : IDL.Nat,
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : Role,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InviteStatus = IDL.Variant({
    'revoked' : IDL.Null,
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const SalesmanInvite = IDL.Record({
    'id' : IDL.Nat,
    'status' : InviteStatus,
    'contactInfo' : IDL.Text,
    'businessId' : IDL.Nat,
    'invitedAt' : IDL.Int,
  });
  const Time = IDL.Int;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(ExternalBlob),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'addProductVariant' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, ProductState],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBill' : IDL.Func([IDL.Nat], [], []),
    'createBillToken' : IDL.Func(
        [IDL.Nat, IDL.Vec(BillItem), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deactivateSalesman' : IDL.Func([IDL.Nat], [], []),
    'editProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(ExternalBlob),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'editProductVariant' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'finalizeBill' : IDL.Func([IDL.Nat], [], []),
    'getActivityLogs' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SalesmanActivityLog)],
        ['query'],
      ),
    'getAllBills' : IDL.Func([], [IDL.Vec(BillToken)], ['query']),
    'getAllBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
    'getAllProductVariants' : IDL.Func(
        [],
        [IDL.Vec(ProductVariant)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBillsForBusiness' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BillToken)],
        ['query'],
      ),
    'getBusiness' : IDL.Func([IDL.Nat], [Business], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvitesForBusiness' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SalesmanInvite)],
        ['query'],
      ),
    'getPendingBills' : IDL.Func([IDL.Nat], [IDL.Vec(BillToken)], ['query']),
    'getProductsForBusiness' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSalesmanActivityLogs' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SalesmanActivityLog)],
        ['query'],
      ),
    'getTimeDiff' : IDL.Func([Time, Time], [IDL.Int], ['query']),
    'getTotalBillsCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getTotalSales' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVariantsForProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductVariant)],
        ['query'],
      ),
    'inviteSalesman' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lockVariant' : IDL.Func([IDL.Nat], [], []),
    'lookupInvite' : IDL.Func([IDL.Text], [IDL.Opt(SalesmanInvite)], ['query']),
    'registerBusiness' : IDL.Func(
        [IDL.Text, BusinessType, SubscriptionStatus, IDL.Int, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'releaseVariantLock' : IDL.Func([IDL.Nat], [], []),
    'revokeInvite' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Role, IDL.Bool],
        [],
        [],
      ),
    'updateSubscription' : IDL.Func([IDL.Nat, SubscriptionStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };