/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BillItem {
    priceAtSale: bigint;
    variantId: bigint;
    quantity: bigint;
}
export type Time = bigint;
export interface Business {
    id: bigint;
    trialEndDate: bigint;
    owner: Principal;
    name: string;
    businessType: BusinessType;
    subscriptionStatus: SubscriptionStatus;
    trialStartDate: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BillToken {
    id: bigint;
    status: BillStatus;
    businessId: bigint;
    createdAt: bigint;
    finalizedAt?: bigint;
    totalAmount: bigint;
    items: Array<BillItem>;
    salesmanId: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ProductVariant {
    id: bigint;
    variantName: string;
    productId: bigint;
    stockCount: bigint;
    state: ProductState;
    lockedBy?: bigint;
    price: bigint;
}
export interface SalesmanActivityLog {
    action: string;
    businessId: bigint;
    metadata: string;
    logId: bigint;
    timestamp: bigint;
    salesmanId: bigint;
}
export interface SalesmanInvite {
    id: bigint;
    status: InviteStatus;
    contactInfo: string;
    businessId: bigint;
    invitedAt: bigint;
}
export interface Product {
    id: bigint;
    sku: string;
    imageUrls: Array<ExternalBlob>;
    businessId: bigint;
    name: string;
    description: string;
    isActive: boolean;
    category: string;
    basePrice: bigint;
}
export interface UserProfile {
    principal: Principal;
    businessId: bigint;
    userId: bigint;
    name: string;
    role: Role;
    isActive: boolean;
    email: string;
    phone: string;
}
export enum BillStatus {
    cancelled = "cancelled",
    pending = "pending",
    finalized = "finalized"
}
export enum BusinessType {
    clothing = "clothing",
    groceries = "groceries",
    general = "general",
    electronics = "electronics"
}
export enum InviteStatus {
    revoked = "revoked",
    pending = "pending",
    accepted = "accepted"
}
export enum ProductState {
    sold = "sold",
    locked = "locked",
    available = "available"
}
export enum Role {
    salesman = "salesman",
    owner = "owner"
}
export enum SubscriptionStatus {
    trial = "trial",
    active = "active",
    expired = "expired",
    grace = "grace"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(businessId: bigint, name: string, sku: string, category: string, description: string, basePrice: bigint, imageUrls: Array<ExternalBlob>, isActive: boolean): Promise<bigint>;
    addProductVariant(productId: bigint, variantName: string, price: bigint, stockCount: bigint, state: ProductState): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBill(billId: bigint): Promise<void>;
    createBillToken(businessId: bigint, items: Array<BillItem>, totalAmount: bigint): Promise<bigint>;
    deactivateSalesman(salesmanUserId: bigint): Promise<void>;
    editProduct(productId: bigint, name: string, sku: string, category: string, description: string, basePrice: bigint, imageUrls: Array<ExternalBlob>, isActive: boolean): Promise<void>;
    editProductVariant(variantId: bigint, variantName: string, price: bigint, stockCount: bigint): Promise<void>;
    finalizeBill(billId: bigint): Promise<void>;
    getActivityLogs(businessId: bigint): Promise<Array<SalesmanActivityLog>>;
    getAllBills(): Promise<Array<BillToken>>;
    getAllBusinesses(): Promise<Array<Business>>;
    getAllProductVariants(): Promise<Array<ProductVariant>>;
    getAllProducts(): Promise<Array<Product>>;
    getBillsForBusiness(businessId: bigint): Promise<Array<BillToken>>;
    getBusiness(businessId: bigint): Promise<Business>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInvitesForBusiness(businessId: bigint): Promise<Array<SalesmanInvite>>;
    getPendingBills(businessId: bigint): Promise<Array<BillToken>>;
    getProductsForBusiness(businessId: bigint): Promise<Array<Product>>;
    getSalesmanActivityLogs(salesmanUserId: bigint): Promise<Array<SalesmanActivityLog>>;
    getTimeDiff(time1: Time, time2: Time): Promise<bigint>;
    getTotalBillsCount(businessId: bigint): Promise<bigint>;
    getTotalSales(businessId: bigint): Promise<bigint>;
    getUserById(userId: bigint): Promise<UserProfile | null>;
    getUserProfile(userPrincipal: Principal): Promise<UserProfile | null>;
    getVariantsForProduct(productId: bigint): Promise<Array<ProductVariant>>;
    inviteSalesman(businessId: bigint, contactInfo: string): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    lockVariant(variantId: bigint): Promise<void>;
    lookupInvite(contactInfo: string): Promise<SalesmanInvite | null>;
    registerBusiness(name: string, businessType: BusinessType, subscriptionStatus: SubscriptionStatus, trialStartDate: bigint, trialEndDate: bigint): Promise<bigint>;
    releaseVariantLock(variantId: bigint): Promise<void>;
    revokeInvite(inviteId: bigint): Promise<void>;
    saveCallerUserProfile(name: string, email: string, phone: string, businessId: bigint, role: Role, isActive: boolean): Promise<void>;
    updateSubscription(businessId: bigint, newStatus: SubscriptionStatus): Promise<void>;
}
import type { BillItem as _BillItem, BillStatus as _BillStatus, BillToken as _BillToken, Business as _Business, BusinessType as _BusinessType, ExternalBlob as _ExternalBlob, InviteStatus as _InviteStatus, Product as _Product, ProductState as _ProductState, ProductVariant as _ProductVariant, Role as _Role, SalesmanInvite as _SalesmanInvite, SubscriptionStatus as _SubscriptionStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: Array<ExternalBlob>, arg7: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async addProductVariant(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: ProductState): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductVariant(arg0, arg1, arg2, arg3, to_candid_ProductState_n10(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductVariant(arg0, arg1, arg2, arg3, to_candid_ProductState_n10(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBill(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBill(arg0);
            return result;
        }
    }
    async createBillToken(arg0: bigint, arg1: Array<BillItem>, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBillToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBillToken(arg0, arg1, arg2);
            return result;
        }
    }
    async deactivateSalesman(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateSalesman(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateSalesman(arg0);
            return result;
        }
    }
    async editProduct(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: Array<ExternalBlob>, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editProduct(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProduct(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async editProductVariant(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editProductVariant(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProductVariant(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async finalizeBill(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeBill(arg0);
            return result;
        }
    }
    async getActivityLogs(arg0: bigint): Promise<Array<SalesmanActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogs(arg0);
            return result;
        }
    }
    async getAllBills(): Promise<Array<BillToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBusinesses(): Promise<Array<Business>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBusinesses();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBusinesses();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProductVariants(): Promise<Array<ProductVariant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductVariants();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductVariants();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBillsForBusiness(arg0: bigint): Promise<Array<BillToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillsForBusiness(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillsForBusiness(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusiness(arg0: bigint): Promise<Business> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusiness(arg0);
                return from_candid_Business_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusiness(arg0);
            return from_candid_Business_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvitesForBusiness(arg0: bigint): Promise<Array<SalesmanInvite>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvitesForBusiness(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvitesForBusiness(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingBills(arg0: bigint): Promise<Array<BillToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingBills(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingBills(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsForBusiness(arg0: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsForBusiness(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsForBusiness(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesmanActivityLogs(arg0: bigint): Promise<Array<SalesmanActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesmanActivityLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesmanActivityLogs(arg0);
            return result;
        }
    }
    async getTimeDiff(arg0: Time, arg1: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimeDiff(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimeDiff(arg0, arg1);
            return result;
        }
    }
    async getTotalBillsCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalBillsCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalBillsCount(arg0);
            return result;
        }
    }
    async getTotalSales(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSales(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSales(arg0);
            return result;
        }
    }
    async getUserById(arg0: bigint): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVariantsForProduct(arg0: bigint): Promise<Array<ProductVariant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVariantsForProduct(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVariantsForProduct(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async inviteSalesman(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteSalesman(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteSalesman(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async lockVariant(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.lockVariant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockVariant(arg0);
            return result;
        }
    }
    async lookupInvite(arg0: string): Promise<SalesmanInvite | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupInvite(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupInvite(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerBusiness(arg0: string, arg1: BusinessType, arg2: SubscriptionStatus, arg3: bigint, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBusiness(arg0, to_candid_BusinessType_n50(this._uploadFile, this._downloadFile, arg1), to_candid_SubscriptionStatus_n52(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBusiness(arg0, to_candid_BusinessType_n50(this._uploadFile, this._downloadFile, arg1), to_candid_SubscriptionStatus_n52(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async releaseVariantLock(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.releaseVariantLock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.releaseVariantLock(arg0);
            return result;
        }
    }
    async revokeInvite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeInvite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeInvite(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Role, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3, to_candid_Role_n54(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3, to_candid_Role_n54(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateSubscription(arg0: bigint, arg1: SubscriptionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscription(arg0, to_candid_SubscriptionStatus_n52(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscription(arg0, to_candid_SubscriptionStatus_n52(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BillStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillStatus): BillStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_BillToken_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillToken): BillToken {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_BusinessType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessType): BusinessType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Business_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Business): Business {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InviteStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteStatus): InviteStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ProductState_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductState): ProductState {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ProductVariant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductVariant): ProductVariant {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SalesmanInvite_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesmanInvite): SalesmanInvite {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalesmanInvite]): SalesmanInvite | null {
    return value.length === 0 ? null : from_candid_SalesmanInvite_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BillStatus;
    businessId: bigint;
    createdAt: bigint;
    finalizedAt: [] | [bigint];
    totalAmount: bigint;
    items: Array<_BillItem>;
    salesmanId: bigint;
}): {
    id: bigint;
    status: BillStatus;
    businessId: bigint;
    createdAt: bigint;
    finalizedAt?: bigint;
    totalAmount: bigint;
    items: Array<BillItem>;
    salesmanId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BillStatus_n17(_uploadFile, _downloadFile, value.status),
        businessId: value.businessId,
        createdAt: value.createdAt,
        finalizedAt: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.finalizedAt)),
        totalAmount: value.totalAmount,
        items: value.items,
        salesmanId: value.salesmanId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    trialEndDate: bigint;
    owner: Principal;
    name: string;
    businessType: _BusinessType;
    subscriptionStatus: _SubscriptionStatus;
    trialStartDate: bigint;
}): {
    id: bigint;
    trialEndDate: bigint;
    owner: Principal;
    name: string;
    businessType: BusinessType;
    subscriptionStatus: SubscriptionStatus;
    trialStartDate: bigint;
} {
    return {
        id: value.id,
        trialEndDate: value.trialEndDate,
        owner: value.owner,
        name: value.name,
        businessType: from_candid_BusinessType_n23(_uploadFile, _downloadFile, value.businessType),
        subscriptionStatus: from_candid_SubscriptionStatus_n25(_uploadFile, _downloadFile, value.subscriptionStatus),
        trialStartDate: value.trialStartDate
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    variantName: string;
    productId: bigint;
    stockCount: bigint;
    state: _ProductState;
    lockedBy: [] | [bigint];
    price: bigint;
}): {
    id: bigint;
    variantName: string;
    productId: bigint;
    stockCount: bigint;
    state: ProductState;
    lockedBy?: bigint;
    price: bigint;
} {
    return {
        id: value.id,
        variantName: value.variantName,
        productId: value.productId,
        stockCount: value.stockCount,
        state: from_candid_ProductState_n30(_uploadFile, _downloadFile, value.state),
        lockedBy: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.lockedBy)),
        price: value.price
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    sku: string;
    imageUrls: Array<_ExternalBlob>;
    businessId: bigint;
    name: string;
    description: string;
    isActive: boolean;
    category: string;
    basePrice: bigint;
}): Promise<{
    id: bigint;
    sku: string;
    imageUrls: Array<ExternalBlob>;
    businessId: bigint;
    name: string;
    description: string;
    isActive: boolean;
    category: string;
    basePrice: bigint;
}> {
    return {
        id: value.id,
        sku: value.sku,
        imageUrls: await from_candid_vec_n35(_uploadFile, _downloadFile, value.imageUrls),
        businessId: value.businessId,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        category: value.category,
        basePrice: value.basePrice
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    businessId: bigint;
    userId: bigint;
    name: string;
    role: _Role;
    isActive: boolean;
    email: string;
    phone: string;
}): {
    principal: Principal;
    businessId: bigint;
    userId: bigint;
    name: string;
    role: Role;
    isActive: boolean;
    email: string;
    phone: string;
} {
    return {
        principal: value.principal,
        businessId: value.businessId,
        userId: value.userId,
        name: value.name,
        role: from_candid_Role_n40(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        phone: value.phone
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InviteStatus;
    contactInfo: string;
    businessId: bigint;
    invitedAt: bigint;
}): {
    id: bigint;
    status: InviteStatus;
    contactInfo: string;
    businessId: bigint;
    invitedAt: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InviteStatus_n47(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        businessId: value.businessId,
        invitedAt: value.invitedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    finalized: null;
}): BillStatus {
    return "cancelled" in value ? BillStatus.cancelled : "pending" in value ? BillStatus.pending : "finalized" in value ? BillStatus.finalized : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing: null;
} | {
    groceries: null;
} | {
    general: null;
} | {
    electronics: null;
}): BusinessType {
    return "clothing" in value ? BusinessType.clothing : "groceries" in value ? BusinessType.groceries : "general" in value ? BusinessType.general : "electronics" in value ? BusinessType.electronics : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    active: null;
} | {
    expired: null;
} | {
    grace: null;
}): SubscriptionStatus {
    return "trial" in value ? SubscriptionStatus.trial : "active" in value ? SubscriptionStatus.active : "expired" in value ? SubscriptionStatus.expired : "grace" in value ? SubscriptionStatus.grace : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    locked: null;
} | {
    available: null;
}): ProductState {
    return "sold" in value ? ProductState.sold : "locked" in value ? ProductState.locked : "available" in value ? ProductState.available : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salesman: null;
} | {
    owner: null;
}): Role {
    return "salesman" in value ? Role.salesman : "owner" in value ? Role.owner : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revoked: null;
} | {
    pending: null;
} | {
    accepted: null;
}): InviteStatus {
    return "revoked" in value ? InviteStatus.revoked : "pending" in value ? InviteStatus.pending : "accepted" in value ? InviteStatus.accepted : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BillToken>): Array<BillToken> {
    return value.map((x)=>from_candid_BillToken_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Business>): Array<Business> {
    return value.map((x)=>from_candid_Business_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductVariant>): Array<ProductVariant> {
    return value.map((x)=>from_candid_ProductVariant_n28(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n33(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesmanInvite>): Array<SalesmanInvite> {
    return value.map((x)=>from_candid_SalesmanInvite_n45(_uploadFile, _downloadFile, x));
}
function to_candid_BusinessType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): _BusinessType {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ProductState_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductState): _ProductState {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductState): {
    sold: null;
} | {
    locked: null;
} | {
    available: null;
} {
    return value == ProductState.sold ? {
        sold: null
    } : value == ProductState.locked ? {
        locked: null
    } : value == ProductState.available ? {
        available: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): {
    clothing: null;
} | {
    groceries: null;
} | {
    general: null;
} | {
    electronics: null;
} {
    return value == BusinessType.clothing ? {
        clothing: null
    } : value == BusinessType.groceries ? {
        groceries: null
    } : value == BusinessType.general ? {
        general: null
    } : value == BusinessType.electronics ? {
        electronics: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    trial: null;
} | {
    active: null;
} | {
    expired: null;
} | {
    grace: null;
} {
    return value == SubscriptionStatus.trial ? {
        trial: null
    } : value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.expired ? {
        expired: null
    } : value == SubscriptionStatus.grace ? {
        grace: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    salesman: null;
} | {
    owner: null;
} {
    return value == Role.salesman ? {
        salesman: null
    } : value == Role.owner ? {
        owner: null
    } : value;
}
async function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
